const CATEGORIES=['Colazione','Pranzo','Cena','Trasporti','Spese Hotel','Altro'];
const PROOFS=['Nulla - forfettario pasti','Scontrino','Ricevuta online'];
const MEALS=new Set(['Colazione','Pranzo','Cena']);
const KEY='trasferteManagerV3';
let state=loadState();

function initial(){return{settings:{daily:0,meal:0,travelRate:0},trips:[],expenses:[],travel:[]}}
function loadState(){try{const v=JSON.parse(localStorage.getItem(KEY));if(v)return v;for(const k of ['trasferteManagerV2','trasferteManagerV1']){const old=JSON.parse(localStorage.getItem(k));if(old){localStorage.setItem(KEY,JSON.stringify(old));return old}}}catch{}return initial()}
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
const eur=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const n=v=>Number(v||0);const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function days(a,b){if(!a||!b)return 0;return Math.floor((new Date(b+'T00:00:00')-new Date(a+'T00:00:00'))/86400000)+1}
function outside(start,end){const [sh,sm]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number);let s=sh*60+sm,e=eh*60+em;if(e<s)return null;return (Math.max(0,Math.min(e,465)-s)+Math.max(0,e-Math.max(s,990)))/60}
function stats(t){const ex=state.expenses.filter(x=>x.tripId===t.id),tr=state.travel.filter(x=>x.tripId===t.id);const d=days(t.start,t.end),mealCount=ex.filter(x=>MEALS.has(x.category)).length,mealActual=ex.filter(x=>MEALS.has(x.category)).reduce((a,x)=>a+n(x.amount),0),total=ex.reduce((a,x)=>a+n(x.amount),0),personal=ex.filter(x=>x.payment==='Mio').reduce((a,x)=>a+n(x.amount),0),company=ex.filter(x=>x.payment==='Aziendale').reduce((a,x)=>a+n(x.amount),0),refund=ex.filter(x=>x.payment==='Mio'&&['Trasporti','Spese Hotel','Altro'].includes(x.category)).reduce((a,x)=>a+n(x.amount),0),hours=tr.reduce((a,x)=>a+n(x.outsideHours),0),travelPay=hours*n(t.travelRate),daily=d*n(t.daily),mealAllowance=mealCount*n(t.mealAllowance),km=t.kmEnabled==='yes'?n(t.kmAmount):0;return{d,total,personal,company,refund,hours,travelPay,daily,mealAllowance,mealActual,km,balance:daily+mealAllowance+km+travelPay-mealActual}}
function overall(){return state.trips.reduce((a,t)=>{const s=stats(t);for(const k of ['total','personal','company','refund','balance'])a[k]+=s[k];return a},{total:0,personal:0,company:0,refund:0,balance:0})}
function tripOptions(){return '<option value="">Seleziona...</option>'+state.trips.map(t=>`<option value="${esc(t.id)}">${esc(t.id)} — ${esc(t.description)}</option>`).join('')}
function setupOptions(){expenseTrip.innerHTML=travelTrip.innerHTML=tripOptions();expenseCategory.innerHTML=CATEGORIES.map(c=>`<option>${c}</option>`).join('');expenseProof.innerHTML=PROOFS.map(p=>`<option>${p}</option>`).join('');filterTrip.innerHTML='<option value="">Tutte le trasferte</option>'+state.trips.map(t=>`<option value="${esc(t.id)}">${esc(t.id)}</option>`).join('');filterCategory.innerHTML='<option value="">Tutte le categorie</option>'+CATEGORIES.map(c=>`<option>${c}</option>`).join('')}
function tripCard(t,full=false){const s=stats(t),cls=s.balance>=0?'good':'bad';return `<article class="trip-card"><div class="trip-top"><div><h3>${esc(t.description)}</h3><p>${esc(t.id)} · ${esc(t.start)} → ${esc(t.end)}</p></div><span class="balance-pill ${cls}">${s.balance>=0?'+':''}${eur(s.balance)}</span></div><div class="trip-stats"><div class="mini"><span>Spese</span><strong>${eur(s.total)}</strong></div><div class="mini"><span>Da ricevere</span><strong>${eur(s.refund)}</strong></div><div class="mini"><span>Ore viaggio</span><strong>${s.hours.toFixed(1)} h</strong></div></div>${full?`<div class="trip-actions"><button class="ghost" onclick="prefillExpense('${encodeURIComponent(t.id)}')">＋ Spesa</button><button class="ghost" onclick="prefillTravel('${encodeURIComponent(t.id)}')">＋ Viaggio</button><button class="danger" onclick="deleteTrip('${encodeURIComponent(t.id)}')">Elimina</button></div>`:''}</article>`}
function renderHome(){const o=overall();balanceTotal.textContent=eur(o.balance);refundTotal.textContent=eur(o.refund);personalTotal.textContent=eur(o.personal);expensesTotal.textContent=eur(o.total);companyTotal.textContent=eur(o.company);balanceMeta.textContent=state.trips.length?`${state.trips.length} trasferte registrate`:'Nessuna trasferta registrata';const recent=[...state.trips].sort((a,b)=>String(b.start).localeCompare(String(a.start))).slice(0,4);homeTrips.innerHTML=recent.map(t=>tripCard(t)).join('')||'<div class="empty">Nessuna trasferta. Tocca + per iniziare.</div>';const icons={Colazione:'☕',Pranzo:'🍽️',Cena:'🌙',Trasporti:'🚕','Spese Hotel':'🏨',Altro:'•'};categorySummary.innerHTML=CATEGORIES.map(c=>{const rows=state.expenses.filter(x=>x.category===c),sum=rows.reduce((a,x)=>a+n(x.amount),0);return `<div class="category-row"><div class="category-left"><span class="cat-icon">${icons[c]}</span><div><strong>${c}</strong><br><small>${rows.length} voci</small></div></div><strong>${eur(sum)}</strong></div>`}).join('')}
function renderTrips(){tripsList.innerHTML=state.trips.map(t=>tripCard(t,true)).join('')||'<div class="empty">Nessuna trasferta registrata.</div>'}
function expenseIcon(c){return{Colazione:'☕',Pranzo:'🍽️',Cena:'🌙',Trasporti:'🚕','Spese Hotel':'🏨',Altro:'•'}[c]||'€'}
function renderExpenses(){const ft=filterTrip.value||'',fc=filterCategory.value||'';const rows=state.expenses.filter(x=>(!ft||x.tripId===ft)&&(!fc||x.category===fc)).sort((a,b)=>String(b.date).localeCompare(String(a.date)));expensesList.innerHTML=rows.map(x=>`<article class="expense-row"><div class="expense-icon">${expenseIcon(x.category)}</div><div><h4>${esc(x.category)}</h4><p>${esc(x.tripId)} · ${esc(x.date)}${x.details?' · '+esc(x.details):''}</p></div><div class="expense-right"><strong>${eur(x.amount)}</strong><small>${esc(x.payment)}</small><br><button class="danger" onclick="deleteExpense('${x.id}')">×</button></div></article>`).join('')||'<div class="empty">Nessuna spesa registrata.</div>'}
function renderTravel(){travelList.innerHTML=[...state.travel].sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(x=>{const t=state.trips.find(y=>y.id===x.tripId);return `<article class="expense-row"><div class="expense-icon">⏱</div><div><h4>${n(x.outsideHours).toFixed(2)} ore rimborsabili</h4><p>${esc(x.tripId)} · ${esc(x.date)} · ${esc(x.start)} → ${esc(x.end)}</p></div><div class="expense-right"><strong>${eur(n(x.outsideHours)*n(t?.travelRate))}</strong><button class="danger" onclick="deleteTravel('${x.id}')">×</button></div></article>`}).join('')||'<div class="empty">Nessuna ora viaggio registrata.</div>'}
function renderSettings(){defaultDaily.value=state.settings.daily||'';defaultMeal.value=state.settings.meal||'';defaultTravelRate.value=state.settings.travelRate||''}
function renderAll(){setupOptions();renderHome();renderTrips();renderExpenses();renderTravel();renderSettings()}
function go(screen){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(screen).classList.add('active');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.go===screen));scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function openModal(id){backdrop.classList.remove('hidden');document.getElementById(id).classList.remove('hidden')}
function closeModal(){backdrop.classList.add('hidden');document.querySelectorAll('.sheet').forEach(x=>x.classList.add('hidden'))}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openModal(b.dataset.open));document.querySelectorAll('.close').forEach(b=>b.onclick=closeModal);backdrop.onclick=closeModal;quickExpense.onclick=()=>openModal('expenseModal');
tripKmEnabled.onchange=()=>tripKmWrap.classList.toggle('hidden',tripKmEnabled.value!=='yes');
document.querySelectorAll('.pay').forEach(b=>b.onclick=()=>{document.querySelectorAll('.pay').forEach(x=>x.classList.remove('active'));b.classList.add('active');expensePayment.value=b.dataset.pay});
tripForm.onsubmit=e=>{e.preventDefault();tripMsg.className='msg';const tid=tripId.value.trim(),start=tripStart.value,end=tripEnd.value;if(state.trips.some(t=>t.id.toLowerCase()===tid.toLowerCase())){tripMsg.textContent='ID trasferta già esistente.';tripMsg.classList.add('error');return}if(days(start,end)<=0){tripMsg.textContent='Controlla le date.';tripMsg.classList.add('error');return}state.trips.push({id:tid,description:tripDescription.value.trim(),start,end,daily:n(tripDaily.value||state.settings.daily),mealAllowance:n(tripMeal.value||state.settings.meal),kmEnabled:tripKmEnabled.value,kmAmount:tripKmEnabled.value==='yes'?n(tripKm.value):0,travelRate:n(tripTravelRate.value||state.settings.travelRate)});save();e.target.reset();tripKmWrap.classList.add('hidden');closeModal();go('trips')}
expenseForm.onsubmit=e=>{e.preventDefault();expenseMsg.className='msg';const t=state.trips.find(x=>x.id===expenseTrip.value);if(!t){expenseMsg.textContent='Seleziona una trasferta.';expenseMsg.classList.add('error');return}if(expenseDate.value<t.start||expenseDate.value>t.end){expenseMsg.textContent='La data è fuori dal periodo della trasferta.';expenseMsg.classList.add('error');return}state.expenses.push({id:id(),tripId:expenseTrip.value,date:expenseDate.value,category:expenseCategory.value,amount:n(expenseAmount.value),payment:expensePayment.value,proof:expenseProof.value,details:expenseDetails.value.trim()});save();e.target.reset();expensePayment.value='Mio';document.querySelectorAll('.pay').forEach((x,i)=>x.classList.toggle('active',i===0));closeModal();go('expenses')}
travelForm.onsubmit=e=>{e.preventDefault();travelMsg.className='msg';const t=state.trips.find(x=>x.id===travelTrip.value);if(!t){travelMsg.textContent='Seleziona una trasferta.';travelMsg.classList.add('error');return}if(travelDate.value<t.start||travelDate.value>t.end){travelMsg.textContent='La data è fuori dal periodo della trasferta.';travelMsg.classList.add('error');return}const out=outside(travelStart.value,travelEnd.value);if(out===null){travelMsg.textContent='Per viaggi oltre mezzanotte inserisci due righe.';travelMsg.classList.add('error');return}state.travel.push({id:id(),tripId:travelTrip.value,date:travelDate.value,start:travelStart.value,end:travelEnd.value,outsideHours:out,notes:travelNotes.value.trim()});save();e.target.reset();closeModal();go('travel')}
window.prefillExpense=enc=>{openModal('expenseModal');expenseTrip.value=decodeURIComponent(enc)};window.prefillTravel=enc=>{openModal('travelModal');travelTrip.value=decodeURIComponent(enc)};
window.deleteTrip=enc=>{const tid=decodeURIComponent(enc);if(confirm('Eliminare la trasferta e tutti i dati collegati?')){state.trips=state.trips.filter(x=>x.id!==tid);state.expenses=state.expenses.filter(x=>x.tripId!==tid);state.travel=state.travel.filter(x=>x.tripId!==tid);save()}};window.deleteExpense=x=>{if(confirm('Eliminare questa spesa?')){state.expenses=state.expenses.filter(y=>y.id!==x);save()}};window.deleteTravel=x=>{if(confirm('Eliminare questa registrazione?')){state.travel=state.travel.filter(y=>y.id!==x);save()}};
filterTrip.onchange=renderExpenses;filterCategory.onchange=renderExpenses;saveSettings.onclick=()=>{state.settings={daily:n(defaultDaily.value),meal:n(defaultMeal.value),travelRate:n(defaultTravelRate.value)};save();alert('Impostazioni salvate')};
function download(name,text,type='text/plain;charset=utf-8'){const b=new Blob([text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}function csv(rows){return rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n')}
exportBackup.onclick=()=>download('trasferte-backup.json',JSON.stringify(state,null,2),'application/json');importBackup.onchange=async e=>{try{const v=JSON.parse(await e.target.files[0].text());if(!v.trips||!v.expenses)throw 0;state=v;save();alert('Backup importato correttamente')}catch{alert('Backup non valido')}e.target.value=''};exportTrips.onclick=()=>{const r=[['ID','Descrizione','Inizio','Fine','Spese','Rimborso','Saldo']];state.trips.forEach(t=>{const s=stats(t);r.push([t.id,t.description,t.start,t.end,s.total,s.refund,s.balance])});download('trasferte.csv','\uFEFF'+csv(r),'text/csv;charset=utf-8')};exportExpenses.onclick=()=>{const r=[['Data','ID Trasferta','Categoria','Importo','Pagamento','Giustificativo','Dettagli']];state.expenses.forEach(x=>r.push([x.date,x.tripId,x.category,x.amount,x.payment,x.proof,x.details]));download('spese.csv','\uFEFF'+csv(r),'text/csv;charset=utf-8')};
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));today.textContent=new Intl.DateTimeFormat('it-IT',{weekday:'long',day:'numeric',month:'long'}).format(new Date());renderAll();
